city_guide/urls.py
from django.urls import path

from city_guide.views import PlaceListView, PlaceDetailView, PlaceCreateView, PlaceUpdateView, PlaceDeleteView, \
    QuestionCreateView, CommentCreateView

urlpatterns = [

    path("", PlaceListView.as_view(), name="place-list"),
    path("<int:pk>/", PlaceDetailView.as_view(), name="place-detail"),
    path("create/", PlaceCreateView.as_view(), name="place-create"),
    path("<int:pk>/update/", PlaceUpdateView.as_view(), name="place-update"),
    path("<int:pk>/delete/", PlaceDeleteView.as_view(), name="place-delete"),

    path("<int:pk>/question/create/", QuestionCreateView.as_view(), name="question-create"),
    path("<int:pk>/question/<int:question_pk>/comment/", CommentCreateView.as_view(), name="question-comment-create"),
    path("<int:pk>/comment/create/", CommentCreateView.as_view(), name="comment-create"),
]

app_name = "city_guide"

foursquare/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include("city_guide.urls", namespace="city_guide")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

city_guide/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models


class Place(models.Model):
    image_url = models.URLField()
    name = models.CharField(max_length=150)
    location = models.CharField(max_length=150)
    description = models.TextField()

    def __str__(self):
        return self.name


class Comment(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    place = models.ForeignKey("Place", on_delete=models.CASCADE, related_name="comments")
    question = models.ForeignKey("Question", on_delete=models.CASCADE, null=True, blank=True, related_name="comments")
    text = models.TextField()
    media_url = models.URLField(null=True, blank=True)

    def __str__(self):
        return f"{self.created_at} {self.user.username} {self.place.name}"


class Question(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    place = models.ForeignKey("Place", on_delete=models.CASCADE, related_name="questions")
    text = models.TextField()

    def __str__(self):
        return f"{self.created_at} {self.user.username} {self.place.name}"


class User(AbstractUser):
    pass

city_guide/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from city_guide.models import Place, Question, Comment


class PlaceListView(generic.ListView):
    model = Place


class PlaceDetailView(generic.DetailView):
    model = Place


class PlaceCreateView(generic.CreateView):
    model = Place
    fields = "__all__"
    success_url = reverse_lazy("city_guide:place-list")


class PlaceUpdateView(generic.UpdateView):
    model = Place
    fields = "__all__"

    def get_success_url(self):
        return reverse_lazy("city_guide:place-detail", args=[self.object.pk])


class PlaceDeleteView(generic.DeleteView):
    model = Place
    success_url = reverse_lazy("city_guide:place-list")


class QuestionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Question
    fields = ["text"]

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.place = get_object_or_404(Place, pk=self.kwargs["pk"])
        return super().form_valid(form)

    # def get_initial(self):
    #     initial = super().get_initial()
    #     initial["place"] = self.kwargs["pk"]
    #     return initial

    def get_success_url(self):
        return reverse_lazy("city_guide:place-detail", args=[self.kwargs["pk"]])


class CommentCreateView(LoginRequiredMixin, generic.CreateView):
    model = Comment
    fields = ["text", "media_url"]

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.place = get_object_or_404(Place, pk=self.kwargs["pk"])

        question_pk = self.kwargs.get("question_pk")
        if question_pk:
            form.instance.question = get_object_or_404(Question, pk=question_pk)

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("city_guide:place-detail", args=[self.kwargs["pk"]])

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>City Guide</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    {% load static %}
      <link rel="stylesheet" href="{% static 'css/styles.css' %}?{% now '1' %}">
{#    <link rel="icon" href="{% static 'images/icon.png' %}">#}
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/city_guide/comment_form.html
{% extends "base.html" %}
{#{% load crispy_forms_filters %}#}

{% block content %}
  <h1>Create comment</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
{#|crispy#}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/city_guide/place_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete place?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/city_guide/place_detail.html
{% extends "base.html" %}
{% block content %}
  <div class="partition">
    <div class="image_detail">
      <img class="image" src="{{ place.image_url }}" alt="Place image">
    </div>
    <div class="info">
      <h1>
        {{ place.name }}
        <a href="{% url 'city_guide:place-delete' pk=place.id %}" class="btn btn-danger link-to-page">
          Delete
        </a>

        <a href="{% url 'city_guide:place-update' pk=place.id %}" class="btn btn-secondary link-to-page">
          Update place
        </a>
      </h1>

      <br>

      <p>
        Location: {{ place.location }}
      </p>
      <p>
        About: {{ place.description }}
      </p>
    </div>
  </div>

  <div class="reviews">
    <h2 class="review_h2">
      Reviews
      {% if user.is_staff %}
        <a href="{% url 'city_guide:question-create' pk=place.id %}" class="btn link-to-page" style="color: dodgerblue">
          Question
        </a>
      {% endif %}

      <a href="{% url 'city_guide:comment-create' pk=place.id %}" class="btn link-to-page" style="color: forestgreen">
        Comment
      </a>
    </h2>

    <hr>

    {% for question in place.questions.all %}
      <div class="question">
        {{ question.user.username }}
        <p style="color: dodgerblue">
          question
        </p>

        <p>
          {{ question.created_at }}
        </p>

        <p>
          {{ question.text }}
          <a href="{% url 'city_guide:question-comment-create' pk=place.id question_pk=question.id %}" class="btn link-to-page" style="color: rebeccapurple">
            Answer
          </a>
        </p>
      </div>

      {% for answer in question.comments.all %}
          <div class="answer">
          {{ answer.user.username }}
          <p style="color: rebeccapurple">
            answer
          </p>

          <p>
            {{ answer.created_at }}
          </p>

          <p>
            {{ answer.text }}
          </p>
        </div>
      {% endfor %}
    {% endfor %}

    {% for comment in place.comments.all %}
      {% if not comment.question %}
        <div class="comments">
          <div>
            {{ comment.user.username }}
            <p style="color: forestgreen">
              comment
            </p>

            <p>
              {{ comment.created_at }}
            </p>

            <p>
              {{ comment.text }}
            </p>
          </div>

          {% if comment.media_url %}
            <div class="image_comment">
              <img class="image" src="{{ comment.media_url }}" alt="Comment media">
            </div>
          {% endif %}
        </div>
      {% endif %}
    {% endfor %}
  </div>
{% endblock %}

templates/city_guide/place_form.html
{% extends "base.html" %}
{#{% load crispy_forms_filters %}#}

{% block content %}
  <h1>{{ object|yesno:"Update place info,Create place"}}</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
{#|crispy#}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/city_guide/place_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Place List
    <a href="{% url 'city_guide:place-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>

  <br>

  {% if place_list %}
    {% for place in place_list %}
      <div class="partition">
        <div class="image_div">
          <img class="image" src="{{ place.image_url }}" alt="Place image">
        </div>
        <div class="info">
          <a href="{% url "city_guide:place-detail" pk=place.id %}">{{ place.name }}</a>
          <p>
            Location: {{ place.location }}
          </p>
        </div>
      </div>
    {% endfor %}
  {% else %}
    <p>There are no places in the service.</p>
  {% endif %}

{% endblock %}

templates/city_guide/question_form.html
{% extends "base.html" %}
{#{% load crispy_forms_filters %}#}

{% block content %}
  <h1>Create question</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
{#|crispy#}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/includes/sidebar.html
<div class="list-group">
  {% if user.is_authenticated %}
    <a class="list-group-item list-group-item-action active">User: {{ user.username }}</a>
    <a href="{% url 'logout'%}?next={{request.path}}" class="list-group-item list-group-item-action">Logout</a>
  {% else %}
    <a href="{% url 'login'%}?next={{request.path}}" class="list-group-item list-group-item-action active">Login</a>
  {% endif %}
</div>

<br>

<div class="list-group">
  <a href="{% url 'city_guide:place-list' %}" class="list-group-item list-group-item-action">Places</a>
</div>